### ISSUE TITLE
Scripts not permitted to use new 

### ISSUE THREAD

**Issue by deveth0** [wcm-io-devops/jenkins-pipeline-library#24]
When setting up the library on a blank jenkins with the latest plugin versions, it's not possible to build as the script uses "illegal" methods which are rejected by the sandbox. 
A quick win solution is to install the [`Permissive Script Security Plugin`](https://plugins.jenkins.io/permissive-script-security) (i know what I'm doing...), but this will remove the complete security layer provided by the sandbox.

```
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new io.wcm.devops.jenkins.pipeline.utils.logging.Logger java.lang.Object
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectNew(StaticWhitelist.java:184)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:170)
	at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:197)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:202)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedConstructor$3.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
	at io.wcm.devops.jenkins.pipeline.utils.maps.MapUtils.<clinit>(MapUtils.groovy:35)
```

**Comment by tobias-richter** [comment]
@deveth0 please have a look at the release notes of https://github.com/wcm-io-devops/jenkins-pipeline-library/releases/tag/1.2.0

It is recommended to setup the Jenkins instance using the Ansible Role [wcm_io_devops.jenkins_pipeline_library](https://galaxy.ansible.com/wcm_io_devops/jenkins_pipeline_library) as statet in the [requirements](https://github.com/wcm-io-devops/jenkins-pipeline-library/blob/1.2.0/docs/requirements.md).

In the requirements documentation also the needed script approvals are documented.

**Comment by tobias-richter** [comment]
@deveth0 can we close this issue?
